#![no_std]
#![no_main]

mod mic;

use core::ffi::c_void;
use core::sync::atomic::{AtomicUsize, Ordering};

use cortex_m_rt::entry;
use defmt_rtt as _;
use iree_embedded::{include_vmfb, Arena, Context, Device, Instance, Result, Tensor};
use panic_probe as _;

// The keyword-spotting model (TFLite-Micro micro_speech, softmax stripped).
// The VM program is embedded here; its kernels are real Cortex-M machine code
// statically linked into this firmware (models/micro_speech.o) and executed in
// place from flash by the static-library loader.
static VMFB: &[u8] = include_vmfb!("../models/micro_speech.vmfb");

extern "C" {
    // Query entry point of the statically linked micro_speech kernels
    // (declared in models/micro_speech.h, generated by iree-compile).
    fn micro_speech_nosm_linked_library_query(
        max_version: u32,
        environment: *const c_void,
    ) -> *const c_void;
}

// Real 1-second "yes" recording (16 kHz mono int16) used as a boot-time
// self-test before the live microphone loop starts.
#[repr(C, align(4))]
struct Align4<T: ?Sized>(T);
static AUDIO: &Align4<[u8]> = &Align4(*include_bytes!("../models/yes_audio.bin"));

const LABELS: [&str; 4] = ["silence", "unknown", "yes", "no"];

// A detection needs the winning yes/no logit to beat the runner-up by this
// much; one window is classified every 250 ms, so weak wins are just noise.
const DETECT_MARGIN: f32 = 2.0;

// ... and the window must contain real acoustic energy. At the SAADC's
// 0..150 mV operating point, quiet-room ambient measures level ~96-112 and
// near-mic speech 200-900 (calibrated on hardware), so gate between them.
// Note the model's "no" class is trigger-happy on ambient noise (an upstream
// micro_speech trait); this gate is what keeps it honest.
const SPEECH_LEVEL: i32 = 160;

// IREE arena (micro_speech needs ~50 KB across context + invoke transients).
static mut HEAP: [u8; 56 * 1024] = [0; 56 * 1024];

// Double-buffered live audio: DMA fills one 250 ms chunk while the CPU
// processes the other. The 1 s model window lives as *features*, not audio:
// the front end runs continuously and keeps a rolling 49x40 spectrogram.
static mut MIC_BUF: [[i16; mic::CHUNK]; mic::RING] = [[0; mic::CHUNK]; mic::RING];

// Small bump pool backing libc malloc/calloc for the front end's one-time state
// allocation (it never frees during operation).
const POOL: usize = 12 * 1024;
static mut FE_POOL: [u8; POOL] = [0; POOL];
static FE_OFF: AtomicUsize = AtomicUsize::new(0);

#[no_mangle]
pub extern "C" fn malloc(size: usize) -> *mut c_void {
    let align = 8usize;
    let off = FE_OFF.load(Ordering::Relaxed);
    let start = (off + align - 1) & !(align - 1);
    let end = start + size;
    if end > POOL {
        return core::ptr::null_mut();
    }
    FE_OFF.store(end, Ordering::Relaxed);
    // SAFETY: single-threaded; [start, end) is a fresh, in-bounds region.
    unsafe { (core::ptr::addr_of_mut!(FE_POOL) as *mut u8).add(start) as *mut c_void }
}

#[no_mangle]
pub extern "C" fn calloc(n: usize, sz: usize) -> *mut c_void {
    let total = n.saturating_mul(sz);
    let p = malloc(total);
    if !p.is_null() {
        // SAFETY: malloc returned a valid `total`-byte region.
        unsafe { core::ptr::write_bytes(p as *mut u8, 0, total) };
    }
    p
}

#[no_mangle]
pub extern "C" fn free(_ptr: *mut c_void) {}

// newlib's malloc/_sbrk reference the `end` heap symbol; we use pools instead.
#[no_mangle]
pub extern "C" fn _sbrk(_incr: isize) -> *mut c_void {
    -1isize as *mut c_void
}

extern "C" {
    fn kws_frontend_init() -> i32;
    // One-shot (resets state): used for the boot self-test on the clip.
    fn kws_features(samples: *const i16, n: i32, out: *mut u8) -> i32;
    // Streaming (state runs continuously): used for the live mic.
    fn kws_frontend_reset();
    fn kws_frontend_push(samples: *const i16, n: i32, mean: i32, gain: i32) -> i32;
    fn kws_frontend_window(out: *mut u8) -> i32;
}

/// Milliseconds elapsed since `start` (DWT cycle counter, 64 MHz core clock).
fn ms_since(start: u32) -> u32 {
    cortex_m::peripheral::DWT::cycle_count().wrapping_sub(start) / 64_000
}

#[entry]
fn main() -> ! {
    defmt::info!("iree-embedded KWS: live mic -> front end -> micro_speech on micro:bit v2");
    // Enable the cycle counter so every stage can be timed.
    let mut cp = cortex_m::Peripherals::take().unwrap();
    cp.DCB.enable_trace();
    cp.DWT.enable_cycle_counter();

    // SAFETY: single core; exclusive access to HEAP, taken once.
    let arena = unsafe { Arena::new(&mut *core::ptr::addr_of_mut!(HEAP)) };
    if let Err(e) = run(&arena) {
        loop {
            defmt::error!(
                "failed: {} (raw {}): {} | largest failed alloc = {} bytes",
                defmt::Debug2Format(&e.code()),
                e.raw_code(),
                e.message(),
                iree_embedded::LAST_ALLOC_FAIL_SIZE.load(Ordering::Relaxed)
            );
            cortex_m::asm::delay(64_000_000); // ~1s
        }
    }
    unreachable!()
}

fn run(arena: &Arena) -> Result<()> {
    // SAFETY: first and only use of the front end this boot.
    unsafe {
        if kws_frontend_init() == 0 {
            defmt::warn!("front end init failed");
        }
    }

    // Bring up the IREE pipeline once; every window reuses it.
    defmt::debug!("step: instance");
    let instance = Instance::new(arena)?;
    defmt::debug!("step: device");
    let device = Device::local_sync_static(arena, &[micro_speech_nosm_linked_library_query])?;
    defmt::debug!("step: context");
    let ctx = Context::new(&instance, &device, VMFB, arena)?;
    defmt::debug!("step: resolve");
    let infer = ctx.resolve("module.tf2onnx")?;

    // Boot self-test on the embedded "yes" clip: proves the whole pipeline
    // before live audio (which depends on mic gain and room noise) runs.
    let audio = &AUDIO.0;
    // SAFETY: the bytes are 4-aligned and an even length of little-endian i16.
    let clip: &[i16] =
        unsafe { core::slice::from_raw_parts(audio.as_ptr() as *const i16, audio.len() / 2) };
    let mut features = [0u8; 49 * 40];
    defmt::debug!("step: self-test front end");
    // SAFETY: features holds 49*40 bytes; clip is a valid slice.
    unsafe { kws_features(clip.as_ptr(), clip.len() as i32, features.as_mut_ptr()) };
    defmt::debug!("step: self-test classify");
    let (label, logits) = classify(&ctx, &device, infer, &features, arena)?;
    defmt::info!("self-test on embedded clip: {} (expected 'yes'), logits = {}", label, logits);

    // A/B: the same clip through the STREAMING path (chunked push + rolling
    // window). Must reproduce the one-shot features byte-for-byte; if not,
    // the streaming front end is at fault rather than the live mic audio.
    // SAFETY: same contracts as the one-shot path above.
    unsafe {
        kws_frontend_reset();
        for c in clip.chunks(mic::CHUNK) {
            kws_frontend_push(c.as_ptr(), c.len() as i32, 0, 1);
        }
    }
    let mut sfeat = [0u8; 49 * 40];
    // SAFETY: sfeat holds 49*40 bytes.
    let sframes = unsafe { kws_frontend_window(sfeat.as_mut_ptr()) };
    let (slabel, slogits) = classify(&ctx, &device, infer, &sfeat, arena)?;
    let sum_oneshot: u32 = features.iter().map(|&b| b as u32).sum();
    let sum_stream: u32 = sfeat.iter().map(|&b| b as u32).sum();
    defmt::info!(
        "streaming self-test: {} ({} frames), logits = {} | feature sums: one-shot {} vs streaming {}",
        slabel,
        sframes,
        slogits,
        sum_oneshot,
        sum_stream
    );

    // Live loop: gapless double-buffered capture; the front end streams and
    // the rolling 1 s spectrogram is classified every 250 ms.
    // SAFETY: nothing else takes the peripherals in this firmware, and
    // MIC_BUF is referenced only here, once.
    let p = unsafe { nrf52833_pac::Peripherals::steal() };
    let mut mic = unsafe {
        mic::Mic::start(&p.P0, &p.PPI, p.SAADC, &mut *core::ptr::addr_of_mut!(MIC_BUF))
    };
    // SAFETY: drop the self-test's residue from the shared front-end state.
    unsafe { kws_frontend_reset() };
    defmt::info!("listening: say 'yes' or 'no' near the mic (sliding 1 s window, 4x/s)");

    let mut cooldown: u32 = 0;
    loop {
        let chunk = mic.wait_chunk();
        let t0 = cortex_m::peripheral::DWT::cycle_count();

        let (mean, level) = mean_and_level(chunk);
        // SAFETY: chunk is a valid slice; the front end copies via scratch.
        unsafe { kws_frontend_push(chunk.as_ptr(), chunk.len() as i32, mean, mic::GAIN) };
        // SAFETY: features holds 49*40 bytes.
        unsafe { kws_frontend_window(features.as_mut_ptr()) };
        let (label, logits) = classify(&ctx, &device, infer, &features, arena)?;

        let compute = ms_since(t0);
        if compute > 240 {
            defmt::warn!("compute {} ms exceeds the 250 ms chunk budget", compute);
        }

        let mut sorted = logits;
        sorted.sort_unstable_by(|a, b| b.total_cmp(a));
        let margin = sorted[0] - sorted[1];
        cooldown = cooldown.saturating_sub(1);
        if (label == "yes" || label == "no")
            && level >= SPEECH_LEVEL
            && margin >= DETECT_MARGIN
            && cooldown == 0
        {
            defmt::info!("==> DETECTED '{}' (margin {})", label, margin);
            cooldown = 4; // suppress duplicates for ~1 s
        }
        // Raw per-window diagnostics; compiled out at the default DEFMT_LOG
        // level (set DEFMT_LOG=debug in .cargo/config.toml when calibrating).
        defmt::debug!(
            "heard: {} | level = {} | compute {} ms | logits = {}",
            label,
            level,
            compute,
            logits
        );
    }
}

/// Run the model over a 49x40 feature window.
fn classify(
    ctx: &Context,
    device: &Device,
    infer: iree_embedded::Function,
    features: &[u8; 49 * 40],
    arena: &Arena,
) -> Result<(&'static str, [f32; 4])> {
    let input = Tensor::from_u8(device, &[1, 49, 40, 1], features)?;
    let outputs = ctx.invoke(infer, &[&input], arena)?;
    let mut logits = [0.0f32; 4];
    outputs[0].read_into_f32(device, &mut logits)?;

    let best = logits
        .iter()
        .enumerate()
        .max_by(|(_, a), (_, b)| a.total_cmp(b))
        .map(|(i, _)| i)
        .unwrap();
    Ok((LABELS[best], logits))
}

/// DC mean of a chunk and its post-gain mean absolute level (loudness).
fn mean_and_level(chunk: &[i16]) -> (i32, i32) {
    let n = chunk.len() as i32;
    let mut sum: i32 = 0;
    for &x in chunk {
        sum += x as i32;
    }
    let mean = sum / n;
    let mut dev: i32 = 0;
    for &x in chunk {
        dev += (x as i32 - mean).abs();
    }
    (mean, dev / n * mic::GAIN)
}
