#![no_std]
#![no_main]

mod mic;

use core::ffi::c_void;
use core::sync::atomic::Ordering;

use cortex_m_rt::entry;
use defmt_rtt as _;
use iree_embedded::{Arena, Context, Device, Instance, Result, Tensor, include_vmfb};
use kws_frontend::{FEATURE_BYTES, Frontend};
use panic_probe as _;

// The keyword-spotting model (TFLite-Micro micro_speech, softmax stripped).
// The VM program is embedded here; its kernels are real Cortex-M machine code
// statically linked into this firmware (models/micro_speech.o) and executed in
// place from flash by the static-library loader.
static VMFB: &[u8] = include_vmfb!("../models/micro_speech.vmfb");

unsafe extern "C" {
    // Query entry point of the statically linked micro_speech kernels
    // (declared in models/micro_speech.h, generated by iree-compile).
    fn micro_speech_nosm_linked_library_query(
        max_version: u32,
        environment: *const c_void,
    ) -> *const c_void;
}

// Real 1-second "yes" recording (16 kHz mono int16) used as a boot-time
// self-test before the live microphone loop starts.
#[repr(C, align(4))]
struct Align4<T: ?Sized>(T);
static AUDIO: &Align4<[u8]> = &Align4(*include_bytes!("../models/yes_audio.bin"));

const LABELS: [&str; 4] = ["silence", "unknown", "yes", "no"];

// A detection needs the winning yes/no logit to beat the runner-up by this
// much; one window is classified every 250 ms, so weak wins are just noise.
const DETECT_MARGIN: f32 = 2.0;

// ... and the window must contain real acoustic energy. At the SAADC's
// 0..150 mV operating point, quiet-room ambient measures level ~96-112 and
// near-mic speech 200-900 (calibrated on hardware), so gate between them.
// Note the model's "no" class is trigger-happy on ambient noise (an upstream
// micro_speech trait); this gate is what keeps it honest.
const SPEECH_LEVEL: i32 = 160;

// IREE arena (micro_speech needs ~50 KB across context + invoke transients).
static mut HEAP: [u8; 56 * 1024] = [0; 56 * 1024];

// Double-buffered live audio: DMA fills one 250 ms chunk while the CPU
// processes the other. The 1 s model window lives as *features*, not audio:
// the front end runs continuously and keeps a rolling 49x40 spectrogram.
static mut MIC_BUF: [[i16; mic::CHUNK]; mic::RING] = [[0; mic::CHUNK]; mic::RING];

// The audio front end (pure Rust, byte-exact port of the TFLM reference);
// ~13 KiB of fixed-point state, kept in a static rather than on the stack.
static mut FRONTEND: Frontend = Frontend::new();

// newlib's malloc/_sbrk reference the `end` heap symbol; the IREE runtime
// allocates from the arena instead, so the libc heap can never grow.
#[unsafe(no_mangle)]
pub extern "C" fn _sbrk(_incr: isize) -> *mut c_void {
    -1isize as *mut c_void
}

/// Milliseconds elapsed since `start` (DWT cycle counter, 64 MHz core clock).
fn ms_since(start: u32) -> u32 {
    cortex_m::peripheral::DWT::cycle_count().wrapping_sub(start) / 64_000
}

#[entry]
fn main() -> ! {
    defmt::info!("iree-embedded KWS: live mic -> front end -> micro_speech on micro:bit v2");
    // Enable the cycle counter so every stage can be timed.
    let mut cp = cortex_m::Peripherals::take().unwrap();
    cp.DCB.enable_trace();
    cp.DWT.enable_cycle_counter();

    // SAFETY: single core; exclusive access to HEAP, taken once.
    let arena = unsafe { Arena::new(&mut *core::ptr::addr_of_mut!(HEAP)) };
    if let Err(e) = run(&arena) {
        loop {
            defmt::error!(
                "failed: {} (raw {}): {} | largest failed alloc = {} bytes",
                defmt::Debug2Format(&e.code()),
                e.raw_code(),
                e.message(),
                iree_embedded::LAST_ALLOC_FAIL_SIZE.load(Ordering::Relaxed)
            );
            cortex_m::asm::delay(64_000_000); // ~1s
        }
    }
    unreachable!()
}

fn run(arena: &Arena) -> Result<()> {
    // SAFETY: single core; exclusive access to FRONTEND, taken once.
    let fe = unsafe { &mut *core::ptr::addr_of_mut!(FRONTEND) };
    fe.init();

    // Bring up the IREE pipeline once; every window reuses it.
    defmt::debug!("step: instance");
    let instance = Instance::new(arena)?;
    defmt::debug!("step: device");
    let device = Device::local_sync_static(arena, &[micro_speech_nosm_linked_library_query])?;
    defmt::debug!("step: context");
    let ctx = Context::new(&instance, &device, VMFB, arena)?;
    defmt::debug!("step: resolve");
    let infer = ctx.resolve("module.tf2onnx")?;

    // Boot self-test on the embedded "yes" clip: proves the whole pipeline
    // before live audio (which depends on mic gain and room noise) runs.
    let audio = &AUDIO.0;
    // SAFETY: the bytes are 4-aligned and an even length of little-endian i16.
    let clip: &[i16] =
        unsafe { core::slice::from_raw_parts(audio.as_ptr() as *const i16, audio.len() / 2) };
    let mut features = [0u8; FEATURE_BYTES];
    defmt::debug!("step: self-test front end");
    fe.features_oneshot(clip, &mut features);
    defmt::debug!("step: self-test classify");
    let (label, logits) = classify(&ctx, &device, infer, &features, arena)?;
    defmt::info!(
        "self-test on embedded clip: {} (expected 'yes'), logits = {}",
        label,
        logits
    );

    // A/B: the same clip through the STREAMING path (chunked push + rolling
    // window). Must reproduce the one-shot features byte-for-byte; if not,
    // the streaming front end is at fault rather than the live mic audio.
    fe.reset();
    for c in clip.chunks(mic::CHUNK) {
        fe.push(c, 0, 1);
    }
    let mut sfeat = [0u8; FEATURE_BYTES];
    let sframes = fe.window(&mut sfeat);
    let (slabel, slogits) = classify(&ctx, &device, infer, &sfeat, arena)?;
    let sum_oneshot: u32 = features.iter().map(|&b| b as u32).sum();
    let sum_stream: u32 = sfeat.iter().map(|&b| b as u32).sum();
    defmt::info!(
        "streaming self-test: {} ({} frames), logits = {} | feature sums: one-shot {} vs streaming {}",
        slabel,
        sframes,
        slogits,
        sum_oneshot,
        sum_stream
    );

    // Live loop: gapless double-buffered capture; the front end streams and
    // the rolling 1 s spectrogram is classified every 250 ms.
    // SAFETY: nothing else takes the peripherals in this firmware, and
    // MIC_BUF is referenced only here, once.
    let p = unsafe { nrf52833_pac::Peripherals::steal() };
    let mut mic = unsafe {
        mic::Mic::start(
            &p.P0,
            &p.PPI,
            p.SAADC,
            &mut *core::ptr::addr_of_mut!(MIC_BUF),
        )
    };
    // Drop the self-test's residue from the front-end state.
    fe.reset();
    defmt::info!("listening: say 'yes' or 'no' near the mic (sliding 1 s window, 4x/s)");

    let mut cooldown: u32 = 0;
    loop {
        let chunk = mic.wait_chunk();
        let t0 = cortex_m::peripheral::DWT::cycle_count();

        let (mean, level) = mean_and_level(chunk);
        fe.push(chunk, mean, mic::GAIN);
        fe.window(&mut features);
        let (label, logits) = classify(&ctx, &device, infer, &features, arena)?;

        let compute = ms_since(t0);
        if compute > 240 {
            defmt::warn!("compute {} ms exceeds the 250 ms chunk budget", compute);
        }

        let mut sorted = logits;
        sorted.sort_unstable_by(|a, b| b.total_cmp(a));
        let margin = sorted[0] - sorted[1];
        cooldown = cooldown.saturating_sub(1);
        if (label == "yes" || label == "no")
            && level >= SPEECH_LEVEL
            && margin >= DETECT_MARGIN
            && cooldown == 0
        {
            defmt::info!("==> DETECTED '{}' (margin {})", label, margin);
            cooldown = 4; // suppress duplicates for ~1 s
        }
        // Raw per-window diagnostics; compiled out at the default DEFMT_LOG
        // level (set DEFMT_LOG=debug in .cargo/config.toml when calibrating).
        defmt::debug!(
            "heard: {} | level = {} | compute {} ms | logits = {}",
            label,
            level,
            compute,
            logits
        );
    }
}

/// Run the model over a 49x40 feature window.
fn classify(
    ctx: &Context,
    device: &Device,
    infer: iree_embedded::Function,
    features: &[u8; FEATURE_BYTES],
    arena: &Arena,
) -> Result<(&'static str, [f32; 4])> {
    let input = Tensor::from_u8(device, &[1, 49, 40, 1], features)?;
    let outputs = ctx.invoke(infer, &[&input], arena)?;
    let mut logits = [0.0f32; 4];
    outputs[0].read_into_f32(device, &mut logits)?;

    let best = logits
        .iter()
        .enumerate()
        .max_by(|(_, a), (_, b)| a.total_cmp(b))
        .map(|(i, _)| i)
        .unwrap();
    Ok((LABELS[best], logits))
}

/// DC mean of a chunk and its post-gain mean absolute level (loudness).
fn mean_and_level(chunk: &[i16]) -> (i32, i32) {
    let n = chunk.len() as i32;
    let mut sum: i32 = 0;
    for &x in chunk {
        sum += x as i32;
    }
    let mean = sum / n;
    let mut dev: i32 = 0;
    for &x in chunk {
        dev += (x as i32 - mean).abs();
    }
    (mean, dev / n * mic::GAIN)
}
