#![no_std]
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code)]

// Raw FFI bindings to the IREE runtime, generated by build.rs. The C wrappers
// for IREE's static-inline helpers are compiled and linked alongside.
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
