#![no_std]
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code)]

// Raw FFI bindings are generated by build.rs and included here (added in the
// "build host IREE runtime and link FFI bindings" task).
